Project: Exploring NYC Public School Test Result Scores

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a maximum score of 800 points. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.
Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend.
The task is answering three key questions about New York City (NYC) public school SAT performance:

1. Which schools produce the highest math scores?
•	Specifically, which schools have an average math SAT score of at least 80%?

2. Who are the top 10 schools based on average results across reading, math, and writing?

3. Which NYC borough has the largest standard deviation for SAT results?

In [1]:
import pandas as pd
data = pd.read_csv('schools.csv')

In [2]:
data.head(2)

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   school_name      375 non-null    object
 1   borough          375 non-null    object
 2   building_code    375 non-null    object
 3   average_math     375 non-null    int64
 4   average_reading  375 non-null    int64
 5   average_writing  375 non-null    int64
 6   percent_tested   355 non-null    float64
dtypes: float64(1), int64(3), object(3)
memory usage: 20.6+ KB

In [4]:
best_math_schools = data[data["average_math"] >= 640][['school_name', 'average_math']].sort_values('average_math', ascending=False)

In [5]:
best_math_schools.head(2)

                      school_name  average_math
88         Stuyvesant High School           754
170  Bronx High School of Science           714

In [6]:
data['total_SAT'] = data['average_reading'] + data['average_math'] + data['average_writing']
data.head(2)

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested,total_SAT
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN,1859
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9,1193

In [7]:
top_10_schools = data.groupby('school_name', as_index=False)['total_SAT'].mean().sort_values('total_SAT', ascending=False).head(10)

In [8]:
top_10_schools

                                           school_name  total_SAT
325                             Stuyvesant High School     2144.0
324                Staten Island Technical High School     2041.0
55                        Bronx High School of Science     2041.0
188  High School of American Studies at Lehman College     2013.0
334                        Townsend Harris High School     1981.0
293  Queens High School for the Sciences at York Co...     1947.0
30                      Bard High School Early College     1914.0
83                      Brooklyn Technical High School     1896.0
121                      Eleanor Roosevelt High School     1889.0
180  High School for Mathematics, Science, and Engi...     1889.0

In [9]:
boroughs = data.groupby('borough')['total_SAT'].agg(['count', 'mean', 'std']).round(2)
largest_std_dev = boroughs[boroughs['std'] == boroughs['std'].max()].reset_index()
largest_std_dev.rename(columns={'count' : 'num_schools', 'mean' : 'average_SAT', 'std' : 'std_SAT'}, inplace=True)

In [13]:
largest_std_dev

     borough  num_schools  average_SAT  std_SAT
0  Manhattan           89      1340.13   230.29